server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mck
    username: root
    password: taeyun1215
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
  web:
    resources:
      static-locations: classpath:/static, classpath:/frontend

logging:
  level:
    org.springframework: debug
    web: debug